spring:
  application:
    name: desafio-final
  datasource:
    url: jdbc:postgresql://localhost:5432/desafio_final?TimeZone=America/Sao_Paulo
    username: postgres
    password: 1928
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  driver-class-name: org.postgresql.Driver